import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import SectionProdutos from '../componentes/SectionProdutos'
import HeaderMobile from '../componentes/HeaderMobile'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Seja bem-vindo | melhores preços do Brasil!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SectionProdutos title="Ofertas do dia"/>
      </main>

    </div>
  )
}
